import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '@/providers/provider';
import { NextNProgressClient } from '@/components';
import { NextUIProvider } from '@nextui-org/system';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ru">
            <body>
                <NextNProgressClient />
                <Providers>
                    <NextUIProvider>{children}</NextUIProvider>
                </Providers>
            </body>
        </html>
    );
}
